import type { INotification } from "./NotificationCard.vue";

export const notifications: INotification[] = [
    {
        id: 1,
        type: 'location',
        message: 'A new location has been added to our platform!',
        time: '2 hours ago',
        link: '/locations/123',
        isRead: false,
    },
    {
        id: 2,
        type: 'offer',
        message: 'Exclusive offer: 20% off on all bookings this weekend!',
        time: '5 hours ago',
        link: '/offers/456',
        isRead: true,
    },
    {
        id: 3,
        type: 'booking',
        message: 'You have a new booking for the location: Paris Beach Resort!',
        time: '1 day ago',
        link: '/bookings/789',
        isRead: false,
    },
    {
        id: 4,
        type: 'reminder',
        message: 'Your booking at Mountain Escape Resort is coming up tomorrow.',
        time: '1 week ago',
        link: '/bookings/101112',
        isRead: false,
    },
    {
        id: 5,
        type: 'offer',
        message: 'Hurry up! 10% off on your next booking if you confirm in the next 24 hours.',
        time: '3 hours ago',
        link: '/offers/112233',
        isRead: true,
    },
    {
        id: 6,
        type: 'location',
        message: 'We just opened a new location in Tokyo!',
        time: '1 hour ago',
        link: '/locations/678',
        isRead: false,
    },
    {
        id: 7,
        type: 'booking',
        message: 'Your booking at Bali Beach Hotel has been confirmed.',
        time: '2 days ago',
        link: '/bookings/456123',
        isRead: true,
    },
    {
        id: 8,
        type: 'reminder',
        message: 'Reminder: Your booking at City View Apartments is tomorrow.',
        time: '4 days ago',
        link: '/bookings/789456',
        isRead: false,
    },
    {
        id: 9,
        type: 'location',
        message: 'New location in New York City added!',
        time: '3 days ago',
        link: '/locations/111213',
        isRead: true,
    },
    {
        id: 10,
        type: 'offer',
        message: 'Limited Time: Get a free night with every 3-night stay during the holiday season!',
        time: '6 hours ago',
        link: '/offers/314159',
        isRead: false,
    },
    {
        id: 11,
        type: 'booking',
        message: 'You have a new booking for the location: Grand Canyon Resort!',
        time: '1 week ago',
        link: '/bookings/246810',
        isRead: true,
    },
    {
        id: 12,
        type: 'reminder',
        message: 'Your booking at Lakeview Retreat is tomorrow!',
        time: '2 weeks ago',
        link: '/bookings/135792',
        isRead: false,
    },
    {
        id: 13,
        type: 'location',
        message: 'New location in Miami added!',
        time: '3 days ago',
        link: '/locations/141516',
        isRead: true,
    },
    {
        id: 14,
        type: 'offer',
        message: 'Special offer: 25% off on family bookings for the holidays!',
        time: '1 day ago',
        link: '/offers/171819',
        isRead: false,
    },
    {
        id: 15,
        type: 'booking',
        message: 'Your booking for the Maui Beach House is confirmed!',
        time: '2 days ago',
        link: '/bookings/202122',
        isRead: true,
    },
    {
        id: 16,
        type: 'reminder',
        message: 'Your booking at Desert Oasis Resort is in 2 days.',
        time: '3 days ago',
        link: '/bookings/222324',
        isRead: true,
    }
];
